Traceback (most recent call last):
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus\browser_decorator.py", line 201, in run_task
    result = func(driver, data)
  File "d:\mada\devlopment\botasaurus_whatsapp-main\whatsapp_automation.py", line 78, in open_whatsapp
    driver.click_element_containing_text("Type a message")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\driver.py", line 1025, in click_element_containing_text
    elem.click(skip_move=skip_move)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\driver.py", line 291, in click
    self._driver._cursor.click(self, skip_move=skip_move)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_humancursor\web_cursor.py", line 83, in click
    self._click(number_of_clicks=number_of_clicks, click_duration=click_duration)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_humancursor\web_cursor.py", line 115, in _click
    self.mouse_release(
    ~~~~~~~~~~~~~~~~~~^
        x=self.origin_coordinates[0],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        y=self.origin_coordinates[1],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_humancursor\web_cursor.py", line 135, in mouse_release
    self.driver.run_cdp_command(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                cdp.input_.dispatch_mouse_event(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
                )
                ^
            )
            ^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\driver.py", line 757, in run_cdp_command
    return self._tab.run_cdp_command(command)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\tab.py", line 933, in run_cdp_command
    return self.send(command)
           ~~~~~~~~~^^^^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\connection.py", line 286, in send
    self.open()
    ~~~~~~~~~^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\connection.py", line 167, in open
    self.wait_for_socket_connection()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\connection.py", line 190, in wait_for_socket_connection
    self.raise_connection_failure_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\connection.py", line 182, in raise_connection_failure_exception
    raise Exception(self._connection_failure_message)
Exception: [WinError 10061] No connection could be made because the target machine actively refused it
